project = "ExampleApp/ExampleApp.xcodeproj"

lane :analyze do
  xcodebuild_analyze(
    project: project,
    scheme: "ExampleApp",
    sdk: "iphonesimulator",
    output: "plist-html",
    output_dir: "tmp",
    static_analyzer: true
  )
end

lane :test do
  xcodebuild_analyze_ensure_no_results(
    project: project,
    scheme: "ExampleApp",
    sdk: "iphonesimulator",
    static_analyzer: true,
    prune_output: true
  )
end
